public enum TokenType {
    NUMBER, PLUS, MINUS, TIMES, DIVIDE, EQUAL, LPAREN, RPAREN,
    STRING, PRINT, VAR, WORD, SUS, SWOTUS,
    LESS_THAN_OR_EQUAL, GREATER_THAN_OR_EQUAL, LESS_THAN, GREATER_THAN, EQUALITY,
    UNKNOWN
}